# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
      :box_name => "centos/7",
      # :public => {:ip => '172.16.1.101', :adapter => 1},
      # :public => {adapter: 1, auto_config: true},
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"}
              ]
  },
:centralRouter => {
      :box_name => "centos/7",
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"}
              ]
},
:testServer1 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testServer2 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testClient1 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testClient2 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end        
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
    end

  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = "true"
  end
  
  
end