# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.50.1", virtualbox__intnet: "dns"
    web.vm.hostname = "web"
    web.vm.provision "shell", run: "always", inline: <<-SHELL
      setenforce 0
      SHELL
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "dns"
    log.vm.hostname = "log"
    log.vm.provision "shell", run: "always", inline: <<-SHELL
      setenforce 0
      SHELL
  end


end
